# Git merge drivers for fleet-uniform generated files.
#
# A generated file has no meaningful 3-way merge: the right answer is not "one
# of the two sides" but "whatever the generator would emit for the merged
# input". These drivers implement that for the two shapes that actually stall
# rebases across the fleet.
#
#   conformist-merge-flake-lock
#     flake.lock. Seeds from OURS, then re-runs `nix flake lock` so the result
#     is a lock consistent with the (already-merged) flake.nix. Ours-biased by
#     design — see the ORDERING note in the script.
#
#   conformist-merge-codegen-header
#     A generated source file whose only conflicting region is its
#     `// Code generated by ...` stamp. 3-way merges the file normally and
#     resolves stamp-only conflict blocks to ours; anything else stays a real
#     conflict.
#
# BOTH FAIL CLOSED. Any condition the driver cannot handle exits non-zero,
# which tells git to record an ordinary conflict for a human. A merge driver
# that guesses is worse than no merge driver, because its output is believed.
#
# These are packages, not linter commands: they are registered once in git
# config (see conformist-git(7)) and invoked by git, not by conformist. The
# `git-merge-drivers` linter only checks that a repo's .gitattributes binds the
# right paths to them.
{ pkgs }:
let
  # Default: an optionally-commented line whose first word after the comment
  # opener is the conventional generated-code marker. Tight enough that a
  # source line merely mentioning the phrase mid-sentence does not match.
  defaultStampRe = "^[[:space:]]*([/#*-]+[[:space:]]*)?Code generated ";

  codegenAwk = ./merge-drivers/codegen-header.awk;
in
{
  flake-lock = pkgs.writeShellApplication {
    name = "conformist-merge-flake-lock";
    runtimeInputs = with pkgs; [
      coreutils
      git
      gnugrep
    ];
    text = ''
      # git invokes this as:  conformist-merge-flake-lock %O %A %B %P
      #   $1 = %O  merge-base version of flake.lock (unused: see ORDERING)
      #   $2 = %A  "ours"; the driver MUST leave the result here
      #   $3 = %B  "theirs"
      #   $4 = %P  the file's repo-relative pathname (locates the flake dir;
      #            defaults to flake.lock so a hand invocation still works)
      #
      # ORDERING / BIAS. This is deliberately NOT a 3-way reconciliation of the
      # lock's JSON. It seeds from ours and re-locks, which means:
      #   - inputs both sides already pin keep OURS' revision (in a rebase,
      #     ours is the onto side — the newer tip — which is the intended
      #     outcome for the incident this driver exists for);
      #   - an input only the merged flake.nix newly requires is resolved fresh
      #     rather than left missing, which is what plain `merge=ours` gets
      #     wrong;
      #   - nothing else churns, because `nix flake lock` does not refresh
      #     already-satisfied entries the way `nix flake update` would.
      # Regenerating from an empty lock would re-resolve every input to latest
      # mid-merge, so seeding is load-bearing, not an optimization.

      ours=$2
      path=''${4:-flake.lock}

      # Guards run cheapest-and-most-specific first, so a failure reports the
      # actual reason rather than whichever check happened to be written first.
      #
      # cwd for a merge driver is not something to rely on; resolve the repo
      # root explicitly so the driver works from anywhere.
      if ! root=$(git rev-parse --show-toplevel 2>/dev/null); then
        echo "conformist-merge-flake-lock: not inside a git worktree; leaving $path conflicted" >&2
        exit 1
      fi

      reldir=$(dirname "$path")
      flakedir=$root
      if [ "$reldir" != "." ]; then
        flakedir=$root/$reldir
      fi

      if [ ! -f "$flakedir/flake.nix" ]; then
        echo "conformist-merge-flake-lock: no flake.nix beside $path; leaving it conflicted" >&2
        exit 1
      fi

      # If flake.nix ITSELF is still unresolved, any lock we generate would be
      # against conflict markers. Git gives no ordering guarantee between the
      # two files' drivers, so this is a real case, not a defensive one.
      if grep -qE '^(<{7}|={7}|>{7}|\|{7})' "$flakedir/flake.nix"; then
        echo "conformist-merge-flake-lock: $reldir/flake.nix still has conflict markers; leaving $path conflicted" >&2
        exit 1
      fi

      if ! command -v nix >/dev/null 2>&1; then
        echo "conformist-merge-flake-lock: nix is not on PATH; leaving $path conflicted" >&2
        exit 1
      fi

      lock=$flakedir/flake.lock
      backup=$(mktemp)
      had_lock=0
      if [ -f "$lock" ]; then
        had_lock=1
        cat "$lock" >"$backup"
      fi

      # Restore the worktree file whatever happens. Git installs $ours at the
      # path immediately after we return, so this is about not leaving a foreign
      # lock behind if we bail early.
      # shellcheck disable=SC2329  # invoked via the EXIT trap below
      restore() {
        if [ "$had_lock" -eq 1 ]; then
          cat "$backup" >"$lock"
        else
          rm -f "$lock"
        fi
        rm -f "$backup"
      }
      trap restore EXIT

      cat "$ours" >"$lock"

      # The flake dir is inside a git repo, so nix reads it as a git tree: it
      # honours the dirty working-tree contents of TRACKED files, and flake.lock
      # is tracked, so the seed above is what nix sees. Deliberately NOT a
      # `path:` flakeref, which would copy the whole directory (.git included)
      # into the store.
      if ! nix flake lock \
        --extra-experimental-features 'nix-command flakes' \
        --no-warn-dirty \
        "$flakedir" >&2; then
        echo "conformist-merge-flake-lock: nix flake lock failed; leaving $path conflicted" >&2
        exit 1
      fi

      cat "$lock" >"$ours"
      echo "conformist-merge-flake-lock: regenerated $path from ours against the merged flake.nix" >&2
      exit 0
    '';
  };

  codegen-header = pkgs.writeShellApplication {
    name = "conformist-merge-codegen-header";
    runtimeInputs = with pkgs; [
      coreutils
      gawk
      git
    ];
    text = ''
      # git invokes this as:  conformist-merge-codegen-header %O %A %B %L %P
      #   $1 = %O  merge-base version
      #   $2 = %A  "ours"; the driver MUST leave the result here
      #   $3 = %B  "theirs"
      #   $4 = %L  conflict marker size (defaults to git's 7)
      #   $5 = %P  the file's repo-relative pathname (diagnostics only)
      #
      # Strategy: an ordinary 3-way merge, then resolve ONLY those conflict
      # blocks that are entirely generator-stamp lines on both sides. A file
      # whose body genuinely diverged still conflicts — this driver narrows the
      # blast radius of a restamp, it does not paper over real edits.

      base=$1
      ours=$2
      theirs=$3
      markers=''${4:-7}
      path=''${5:-a generated file}

      stampre=''${CONFORMIST_CODEGEN_STAMP_RE:-${defaultStampRe}}

      merged=$(mktemp)
      resolved=$(mktemp)
      trap 'rm -f "$merged" "$resolved"' EXIT

      # -p writes to stdout, leaving $ours untouched until we decide. Exit is
      # the conflict count, or negative (>127 once the shell wraps it) on error.
      rc=0
      git merge-file -p \
        --marker-size="$markers" \
        -L ours -L base -L theirs \
        "$ours" "$base" "$theirs" >"$merged" || rc=$?

      if [ "$rc" -eq 0 ]; then
        cat "$merged" >"$ours"
        exit 0
      fi

      if [ "$rc" -gt 127 ]; then
        echo "conformist-merge-codegen-header: git merge-file errored on $path; leaving it conflicted" >&2
        exit 1
      fi

      # The awk program writes the resolved FILE to stdout and the resolved
      # block COUNT to stderr, so stderr is redirected onto the substitution's
      # stdout BEFORE stdout is sent to the file. `>file 2>&1` would instead
      # append the count to the file itself.
      arc=0
      count=$(awk -v msize="$markers" -v stampre="$stampre" \
        -f ${codegenAwk} "$merged" 2>&1 >"$resolved") || arc=$?

      if [ "$arc" -eq 0 ]; then
        cat "$resolved" >"$ours"
        echo "conformist-merge-codegen-header: resolved $count generator-stamp-only conflict(s) to ours in $path" >&2
        exit 0
      fi

      cat "$merged" >"$ours"
      echo "conformist-merge-codegen-header: $path has conflicts beyond the generator stamp; leaving $rc for manual resolution" >&2
      exit 1
    '';
  };
}
