package format_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"code.linenisgreat.com/conformist/config"
	"code.linenisgreat.com/conformist/format"
	"code.linenisgreat.com/conformist/stats"
	"code.linenisgreat.com/conformist/walk"
	"code.linenisgreat.com/purse-first/libs/dewey/pkgs/test_ui"
	"github.com/stretchr/testify/require"
)

// generatedFixtures are the files every skip-generated test walks: two that
// carry the marker in their leading comment block (conformist#133) and two that
// must NOT be treated as generated.
var generatedFixtures = map[string]string{
	"gen.go":        "// Code generated by dagnabit. DO NOT EDIT.\n\npackage p\n",
	"licensed.go":   "// Copyright notice.\n\n// Code generated by tommy. DO NOT EDIT.\r\n\npackage p\n",
	"after-code.go": "package p\n\n// Code generated by x. DO NOT EDIT.\n",
	"no-period.go":  "// Code generated by x. DO NOT EDIT\n\npackage p\n",
}

// handWritten are the fixtures a skip-generated run must still hand to tools.
var handWritten = []string{"after-code.go", "no-period.go"}

func writeGeneratedFixtures(t *test_ui.T, root string) []*walk.File {
	t.Helper()

	files := make([]*walk.File, 0, len(generatedFixtures))

	for rel, content := range generatedFixtures {
		writeFile(t, root, rel, content, 0o644)
		files = append(files, walkFile(t, root, rel))
	}

	return files
}

// logLine is a shell-line tool that appends its file arguments to log.
func logLine(log string) string { return `for f in "$@"; do echo "$f" >> ` + log + `; done` }

func readLogged(t *test_ui.T, log string) []string {
	t.Helper()

	data, err := os.ReadFile(log)
	if os.IsNotExist(err) {
		return nil
	}

	require.NoError(t, err)

	var names []string

	for _, line := range splitLines(string(data)) {
		names = append(names, filepath.Base(line))
	}

	return names
}

func splitLines(s string) []string {
	var out []string

	start := 0

	for i := range len(s) {
		if s[i] == '\n' {
			if i > start {
				out = append(out, s[start:i])
			}

			start = i + 1
		}
	}

	return out
}

func skipGeneratedConfig(root string, skip bool) *config.Config {
	passesFiles := false

	return &config.Config{
		TreeRoot:      root,
		OnUnmatched:   "info",
		SkipGenerated: skip,
		FormatterConfigs: map[string]*config.Formatter{
			"fmt": {
				Command:      logLine(filepath.Join(root, "fmt.log")),
				CheckCommand: logLine(filepath.Join(root, "fmt.log")),
				Includes:     []string{"*.go"},
			},
		},
		LinterConfigs: map[string]*config.Linter{
			"per-file": {
				Command:       logLine(filepath.Join(root, "per-file.log")),
				RepairCommand: logLine(filepath.Join(root, "per-file.log")),
				Includes:      []string{"*.go"},
			},
			"whole-tree": {
				Command:       "echo fired >> " + filepath.Join(root, "whole-tree.log"),
				RepairCommand: "echo fired >> " + filepath.Join(root, "whole-tree.log"),
				Includes:      []string{"gen.go"},
				PassesFiles:   &passesFiles,
			},
		},
	}
}

// TestSkipGeneratedCheck pins conformist#133 in check mode: with skip-generated
// on, files whose leading comment block carries the generated-code marker reach
// neither formatters nor per-file linters, while a whole-tree linter still
// triggers on them — the same contract as a global exclude.
func TestSkipGeneratedCheck(tt *testing.T) {
	for _, skip := range []bool{true, false} {
		t := &test_ui.T{T: tt}
		as := require.New(t)
		root := t.TempDir()
		files := writeGeneratedFixtures(t, root)

		statz := stats.New()

		checker, err := format.NewCompositeChecker(skipGeneratedConfig(root, skip), &statz)
		as.NoError(err)

		_, err = checker.Check(context.Background(), files)
		as.NoError(err)

		_, err = checker.Finalize(context.Background())
		as.NoError(err)

		want := handWritten
		if !skip {
			want = []string{"after-code.go", "gen.go", "licensed.go", "no-period.go"}
		}

		as.ElementsMatch(want, readLogged(t, filepath.Join(root, "fmt.log")), "formatter, skip=%v", skip)
		as.ElementsMatch(want, readLogged(t, filepath.Join(root, "per-file.log")), "per-file linter, skip=%v", skip)
		as.Equal([]string{"fired"}, readLogged(t, filepath.Join(root, "whole-tree.log")), "whole-tree, skip=%v", skip)
	}
}

// TestSkipGeneratedRepair pins conformist#133 for the repair lanes: linter
// repairs and the formatter pass.
func TestSkipGeneratedRepair(tt *testing.T) {
	t := &test_ui.T{T: tt}
	as := require.New(t)
	root := t.TempDir()
	files := writeGeneratedFixtures(t, root)
	cfg := skipGeneratedConfig(root, true)

	statz := stats.New()

	linter, err := format.NewCompositeLinter(cfg, &statz)
	as.NoError(err)
	as.NoError(linter.Repair(context.Background(), files))

	as.ElementsMatch(handWritten, readLogged(t, filepath.Join(root, "per-file.log")))
	as.Equal([]string{"fired"}, readLogged(t, filepath.Join(root, "whole-tree.log")))

	formatter, err := format.NewCompositeFormatter(cfg, &statz, format.BatchSize)
	as.NoError(err)
	as.NoError(formatter.Apply(context.Background(), files))
	as.NoError(formatter.Close(context.Background()))

	as.ElementsMatch(handWritten, readLogged(t, filepath.Join(root, "fmt.log")))
}

// TestSkipGeneratedStdin pins that --stdin content is judged by what was piped
// in (the TmpPath copy), not by whatever sits at the named path.
func TestSkipGeneratedStdin(tt *testing.T) {
	for _, skip := range []bool{true, false} {
		t := &test_ui.T{T: tt}
		as := require.New(t)
		root := t.TempDir()
		cfg := skipGeneratedConfig(root, skip)

		piped := writeFile(t, root, "stdin-copy.go", generatedFixtures["gen.go"], 0o644)
		info, err := os.Stat(piped)
		as.NoError(err)

		// The named path does not exist; only the piped copy does.
		file := &walk.File{Path: filepath.Join(root, "pkgs/x.go"), RelPath: "pkgs/x.go", TmpPath: piped, Info: info}

		statz := stats.New()

		formatter, err := format.NewCompositeFormatter(cfg, &statz, format.BatchSize)
		as.NoError(err)
		as.NoError(formatter.Apply(context.Background(), []*walk.File{file}))
		as.NoError(formatter.Close(context.Background()))

		// Positive control: with skip off the same file reaches the formatter,
		// so an empty log under skip is the skip and not a mismatch.
		if skip {
			as.Empty(readLogged(t, filepath.Join(root, "fmt.log")))
		} else {
			as.Equal([]string{"stdin-copy.go"}, readLogged(t, filepath.Join(root, "fmt.log")))
		}
	}
}
