# Resolve generator-stamp-only conflict blocks in a `git merge-file` result.
#
# Reads the conflicted merge output on stdin/ARGV and writes the resolved file
# to stdout. A conflict block is "stamp-only" when BOTH sides consist entirely
# of generator-stamp lines (matching `stampre`) and blank lines — the shape a
# regenerated file produces when only its `// Code generated by ...` header
# moved. Such a block is resolved to the OURS side. Any other conflict makes
# this exit 1 with no usable output, so the caller falls back to the real
# conflict rather than guessing.
#
# Both sides must be NON-EMPTY to qualify. A block where one side is empty is a
# genuine add/remove of the stamp, not a restamp, and resolving it either way
# would silently add or drop the header.
#
# -v msize   : conflict marker length (git's %L / --marker-size)
# -v stampre : ERE matching a generator stamp line
BEGIN {
    for (i = 0; i < msize; i++) {
        lt = lt "<"
        eq = eq "="
        gt = gt ">"
        bar = bar "|"
    }
    state = "plain"
    nours = 0
    ntheirs = 0
    resolved = 0
    bad = 0
}

function isstamp(line) {
    return (line ~ /^[ \t]*$/) || (line ~ stampre)
}

state == "plain" {
    if (index($0, lt) == 1) {
        state = "ours"
        nours = 0
        ntheirs = 0
        next
    }
    print
    next
}

state == "ours" {
    # The `|||||||` base section only appears under diff3/zdiff3 conflictstyle.
    if (index($0, bar) == 1) { state = "base"; next }
    if (index($0, eq) == 1)  { state = "theirs"; next }
    ours[nours++] = $0
    next
}

# Base section is context only; it never participates in the stamp test.
state == "base" {
    if (index($0, eq) == 1) { state = "theirs"; next }
    next
}

state == "theirs" {
    if (index($0, gt) == 1) {
        ok = (nours > 0 && ntheirs > 0)
        for (i = 0; ok && i < nours; i++)
            if (!isstamp(ours[i])) ok = 0
        for (i = 0; ok && i < ntheirs; i++)
            if (!isstamp(theirs[i])) ok = 0

        if (ok) {
            for (i = 0; i < nours; i++) print ours[i]
            resolved++
        } else {
            bad = 1
        }
        state = "plain"
        next
    }
    theirs[ntheirs++] = $0
    next
}

END {
    # A block we could not resolve, or a truncated block (markers that never
    # closed), means the caller must not trust this output.
    if (bad || state != "plain") exit 1
    # Report the count on stderr so the driver can echo it; stdout is the file.
    printf "%d\n", resolved > "/dev/stderr"
}
